title: "Jesita Wida Ajani"
email: jesita.ajani@bsg.ox.ac.uk
github_username: jesitaajani

logo: /assets/images/profile.jpeg
cv_url: /assets/files/CV_20262.pdf

baseurl: ""
url: "https://gabielsanti.github.io"

# SEO Settings
name: "Ian Gabriel Santillan"
description: "BS Biology graduate, Major in Systematics (Insect Systematics) at the University of the Philippines. Research interests in insect morphology, taxonomy, systematics, and distribution."

author:
  name: "Ian Gabriel Santillan"
  email: "icsantillan@up.edu.ph"

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude common unneeded files
exclude:
  - .DS_Store
  - Gemfile
  - Gemfile.lock
